name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Remplace par le nom de ta branche principale si ce n'est pas "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Assure-toi que cette version de Node.js correspond à ton projet

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Remplace par le répertoire de sortie de ton projet, généralement "build" ou "dist"
